# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm install    
      - name: Test
        run: npm test
        # env:
        #   CI: true
      - name: Generate build
        run: npm run build
