# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
 continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        npm install
        npm run build
        npm test
