# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
   
    steps:  
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 22.
      - run: npm install
      - run: npm test
        
